"""Add notifications fields to User and UserItem

Revision ID: 10630505592e
Revises: ed7b56175e29
Create Date: 2026-03-05 14:12:41.751221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10630505592e'
down_revision = 'ed7b56175e29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notifications_enabled', sa.Boolean(), nullable=True))

    with op.batch_alter_table('user_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notifications_enabled', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_item', schema=None) as batch_op:
        batch_op.drop_column('notifications_enabled')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('notifications_enabled')

    # ### end Alembic commands ###
