"""Add columns to Item table for caching

Revision ID: 2d6c326a7289
Revises: 83f92a2277a4
Create Date: 2026-02-26 20:12:14.797643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d6c326a7289'
down_revision = '83f92a2277a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('currency', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('current_price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('in_stock', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('last_fetched', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_column('last_fetched')
        batch_op.drop_column('in_stock')
        batch_op.drop_column('image_url')
        batch_op.drop_column('current_price')
        batch_op.drop_column('currency')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
